application: mookiesworl
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: css

- url: /ico
  static_dir: ico

- url: /images
  static_dir: images

- url: /js
  static_dir: js
